// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtfAuxkU6t4B-sJKKffPQV51FlawQNt6s',
    appId: '1:460033989305:web:cf35e0917d5fa9db715968',
    messagingSenderId: '460033989305',
    projectId: 'flutter-locafrog-001',
    authDomain: 'flutter-locafrog-001.firebaseapp.com',
    storageBucket: 'flutter-locafrog-001.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvoVcWGZmrbJX10BxPfYDV6w7oJ9o_2ew',
    appId: '1:460033989305:android:0c2ee9cbacaa4ca3715968',
    messagingSenderId: '460033989305',
    projectId: 'flutter-locafrog-001',
    storageBucket: 'flutter-locafrog-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkZIvxigJTDi9HRPbgJu9YueuxZlYsHLE',
    appId: '1:460033989305:ios:a25841c5d5e4a83e715968',
    messagingSenderId: '460033989305',
    projectId: 'flutter-locafrog-001',
    storageBucket: 'flutter-locafrog-001.appspot.com',
    iosClientId:
        '460033989305-gm4hq736nvb96r4nfok9tetimho33hr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLocafrog',
  );
}
